/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeguimientoOrderIdRouteImport } from './routes/seguimiento.$orderId'
import { Route as DriverOrderIdRouteImport } from './routes/driver.$orderId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeguimientoOrderIdRoute = SeguimientoOrderIdRouteImport.update({
  id: '/seguimiento/$orderId',
  path: '/seguimiento/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverOrderIdRoute = DriverOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => DriverRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/driver/$orderId': typeof DriverOrderIdRoute
  '/seguimiento/$orderId': typeof SeguimientoOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/driver/$orderId': typeof DriverOrderIdRoute
  '/seguimiento/$orderId': typeof SeguimientoOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/driver/$orderId': typeof DriverOrderIdRoute
  '/seguimiento/$orderId': typeof SeguimientoOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/driver'
    | '/login'
    | '/driver/$orderId'
    | '/seguimiento/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/driver'
    | '/login'
    | '/driver/$orderId'
    | '/seguimiento/$orderId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/driver'
    | '/login'
    | '/driver/$orderId'
    | '/seguimiento/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DriverRoute: typeof DriverRouteWithChildren
  LoginRoute: typeof LoginRoute
  SeguimientoOrderIdRoute: typeof SeguimientoOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguimiento/$orderId': {
      id: '/seguimiento/$orderId'
      path: '/seguimiento/$orderId'
      fullPath: '/seguimiento/$orderId'
      preLoaderRoute: typeof SeguimientoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/$orderId': {
      id: '/driver/$orderId'
      path: '/$orderId'
      fullPath: '/driver/$orderId'
      preLoaderRoute: typeof DriverOrderIdRouteImport
      parentRoute: typeof DriverRoute
    }
  }
}

interface DriverRouteChildren {
  DriverOrderIdRoute: typeof DriverOrderIdRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverOrderIdRoute: DriverOrderIdRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DriverRoute: DriverRouteWithChildren,
  LoginRoute: LoginRoute,
  SeguimientoOrderIdRoute: SeguimientoOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
